import React, { useState } from "react";
import ReactMarkdown from "react-markdown";
import { useAuth } from "../context/AuthContext";

export const TypingIndicator = () => (
  <div className="flex items-start gap-3 animate-fade-in">
    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-brand-500 to-purple-600 flex items-center justify-center flex-shrink-0 shadow-md">
      <svg className="w-4 h-4 text-white" fill="currentColor" viewBox="0 0 24 24">
        <path d="M13 10V3L4 14h7v7l9-11h-7z" />
      </svg>
    </div>
    <div className="bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 rounded-2xl rounded-tl-sm px-4 py-3 shadow-sm">
      <div className="flex items-center gap-1.5 h-5">
        <span className="typing-dot bg-brand-400" />
        <span className="typing-dot bg-brand-500" />
        <span className="typing-dot bg-brand-600" />
      </div>
    </div>
  </div>
);

const AIImage = ({ src }) => {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  return (
    <div className="mb-3">
      {loading && !error && (
        <div className="w-full h-48 bg-gray-100 dark:bg-gray-700 rounded-xl flex items-center justify-center">
          <div className="flex flex-col items-center gap-2 text-gray-400">
            <svg className="w-8 h-8 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
            </svg>
            <span className="text-xs">Generating image...</span>
          </div>
        </div>
      )}
      {error && (
        <div className="w-full h-24 bg-red-50 dark:bg-red-900/20 rounded-xl flex items-center justify-center text-red-400 text-sm">
          Image failed to load. Please try again.
        </div>
      )}
      <img
        src={src}
        alt="Generated by AI"
        className={`rounded-xl max-w-full shadow-md ${loading || error ? "hidden" : "block"}`}
        onLoad={() => setLoading(false)}
        onError={() => { setLoading(false); setError(true); }}
      />
    </div>
  );
};

const Message = ({ message }) => {
  const { user } = useAuth();
  const isUser = message.role === "user";

  const time = message.timestamp
    ? new Date(message.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
    : "";

  if (isUser) {
    return (
      <div className="flex items-start gap-3 justify-end message-enter">
        <div className="max-w-[75%] md:max-w-[65%] space-y-2">
          {message.filePreview && (
            <div className="flex justify-end">
              <img
                src={message.filePreview}
                alt="Attached"
                className="max-w-[240px] rounded-2xl rounded-tr-sm border-2 border-brand-300/30 shadow-md object-cover"
              />
            </div>
          )}
          {message.fileName && !message.filePreview && (
            <div className="flex justify-end">
              <div className="flex items-center gap-2 px-3 py-2 bg-brand-100 dark:bg-brand-900/30 border border-brand-200 dark:border-brand-800 rounded-xl rounded-tr-sm">
                <svg className="w-4 h-4 text-brand-600 dark:text-brand-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                <span className="text-xs font-medium text-brand-700 dark:text-brand-300 max-w-[160px] truncate">
                  {message.fileName}
                </span>
              </div>
            </div>
          )}
          {message.content && !message.content.startsWith("[Attached file:") && (
            <div className="bg-gradient-to-br from-brand-600 to-purple-600 text-white rounded-2xl rounded-tr-sm px-4 py-3 shadow-md shadow-brand-500/20">
              <p className="text-sm leading-relaxed whitespace-pre-wrap break-words">{message.content}</p>
            </div>
          )}
          {time && <p className="text-xs text-gray-400 dark:text-gray-500 text-right">{time}</p>}
        </div>
        <div className="w-8 h-8 rounded-full bg-gray-300 dark:bg-gray-600 flex items-center justify-center flex-shrink-0 font-semibold text-sm text-gray-700 dark:text-gray-200 shadow-sm">
          {user?.name?.charAt(0).toUpperCase()}
        </div>
      </div>
    );
  }

  return (
    <div className="flex items-start gap-3 message-enter">
      <div className="w-8 h-8 rounded-full bg-gradient-to-br from-brand-500 to-purple-600 flex items-center justify-center flex-shrink-0 shadow-md mt-0.5">
        <svg className="w-4 h-4 text-white" fill="currentColor" viewBox="0 0 24 24">
          <path d="M13 10V3L4 14h7v7l9-11h-7z" />
        </svg>
      </div>
      <div className="max-w-[75%] md:max-w-[70%]">
        <div className="bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 rounded-2xl rounded-tl-sm px-4 py-3 shadow-sm">
          {message.imageUrl && <AIImage src={message.imageUrl} />}
          <div className="text-sm leading-relaxed text-gray-800 dark:text-gray-200 chat-prose">
            <ReactMarkdown>{message.content}</ReactMarkdown>
          </div>
        </div>
        {time && <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">{time}</p>}
      </div>
    </div>
  );
};

export default Message;